service: gatam-gym-api
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs12.x

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          method: POST
          path: /workouts

plugins:
  - serverless-offline
